spring:
  application:
    name: java-springboot-flashcard

  datasource:
    url: jdbc:mysql://localhost:3380/flashcard?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: flashcard
    password: ${FLASHCARD_DB_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        # Enable JPA Auditing
        # enable_lazy_load_no_trans: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # Hibernate parameter binding values
    org.hibernate.orm.jdbc.bind: TRACE

    com.ericbouchut.java.springboot.flashcard: DEBUG
